#theme: jekyll-theme-leaf
title: PasarTani
descriptioon: Sebuah aplikasi yang membantu petani untuk memasarkan hasil taninya. \n GitHub Pages: <a href="https://perwira-az.github.io/PasarTani/">perwira-az.github.io/PasarTani/</a>

